"""Vendored destination / region / airport tables. GENERATED — do not edit.

Regenerate with:  ./sync_catalog.py    (source: flights@7109026)

Hand edits are overwritten and will fail tests/test_catalog.py. To change how
a destination is filed, edit _LONGHAUL_REGIONS in sync_catalog.py and re-run.
"""

GENERATED_FROM = "flights@7109026"

# Tab order on the page. Leading four are the high-volume regions.
REGIONS = (
    ("domestic", "Domestic"),
    ("caribbean", "Caribbean & Mexico"),
    ("canada", "Canada"),
    ("europe", "Europe"),
    ("asia", "Asia"),
    ("mideast", "Middle East"),
    ("africa", "Africa"),
    ("southamerica", "South America"),
    ("hawaii", "Hawaii"),
    ("oceania", "Oceania"),
    ("other", "Other"),
)

# (destination name, region id, airport codes)
DESTINATIONS = (
    ("Los Angeles", "domestic", ("LAX", "BUR", "SNA", "ONT", "LGB")),
    ("Bay Area", "domestic", ("SFO", "OAK", "SJC")),
    ("San Diego", "domestic", ("SAN",)),
    ("Seattle", "domestic", ("SEA",)),
    ("Portland OR", "domestic", ("PDX",)),
    ("Las Vegas", "domestic", ("LAS",)),
    ("Palm Springs", "domestic", ("PSP",)),
    ("Hawaii", "hawaii", ("HNL", "OGG", "KOA", "LIH")),
    ("New York", "domestic", ("JFK", "EWR", "LGA")),
    ("Boston", "domestic", ("BOS",)),
    ("Washington DC", "domestic", ("DCA", "IAD", "BWI")),
    ("Philadelphia", "domestic", ("PHL",)),
    ("Denver", "domestic", ("DEN",)),
    ("Salt Lake City", "domestic", ("SLC",)),
    ("Jackson Hole", "domestic", ("JAC",)),
    ("Bozeman", "domestic", ("BZN",)),
    ("Miami", "domestic", ("MIA", "FLL")),
    ("Orlando", "domestic", ("MCO",)),
    ("New Orleans", "domestic", ("MSY",)),
    ("Austin", "domestic", ("AUS",)),
    ("Chicago", "domestic", ("ORD", "MDW")),
    ("Phoenix", "domestic", ("PHX",)),
    ("Nashville", "domestic", ("BNA",)),
    ("Iceland", "europe", ("KEF",)),
    ("Mexico City", "caribbean", ("MEX",)),
    ("Japan", "asia", ("HND", "NRT", "KIX", "FUK")),
    ("Patagonia", "southamerica", ("FTE", "PUQ", "USH", "BRC")),
    ("New Zealand", "oceania", ("AKL", "CHC", "WLG")),
    ("Southeast Asia", "asia", ("BKK", "DMK", "SGN", "HAN", "KUL", "SIN", "CGK", "MNL", "RGN")),
    ("Norway", "europe", ("OSL", "BGO", "TRD")),
    ("Argentina", "southamerica", ("EZE", "AEP")),
    ("Brazil", "southamerica", ("GRU", "GIG", "BSB", "SSA", "REC")),
    ("Guatemala", "caribbean", ("GUA",)),
    ("Costa Rica", "caribbean", ("SJO", "LIR")),
    ("Puerto Rico", "caribbean", ("SJU",)),
    ("Cancun", "caribbean", ("CUN",)),
    ("Dominican Republic", "caribbean", ("PUJ", "SDQ")),
    ("Jamaica", "caribbean", ("MBJ", "KIN")),
    ("Aruba", "caribbean", ("AUA",)),
    ("Bahamas", "caribbean", ("NAS",)),
    ("Turks & Caicos", "caribbean", ("PLS",)),
    ("Panama", "caribbean", ("PTY",)),
    ("Belize", "caribbean", ("BZE",)),
    ("Honduras", "caribbean", ("RTB", "SAP")),
    ("Cuba", "caribbean", ("HAV",)),
    ("Trinidad", "caribbean", ("POS",)),
    ("Barbados", "caribbean", ("BGI",)),
    ("St. Lucia", "caribbean", ("UVF",)),
    ("Curaçao", "caribbean", ("CUR",)),
    ("Puerto Vallarta", "caribbean", ("PVR",)),
    ("Los Cabos", "caribbean", ("SJD",)),
    ("Cozumel", "caribbean", ("CZM",)),
    ("Toronto", "canada", ("YYZ", "YTZ")),
    ("Montreal", "canada", ("YUL",)),
    ("Vancouver", "canada", ("YVR",)),
    ("Banff", "canada", ("YYC",)),
    ("Paris", "europe", ("CDG", "ORY")),
    ("Nice", "europe", ("NCE",)),
    ("London", "europe", ("LHR", "LGW", "STN")),
    ("Rome", "europe", ("FCO", "CIA")),
    ("Milan", "europe", ("MXP", "LIN", "BGY")),
    ("Florence", "europe", ("FLR", "PSA")),
    ("Venice", "europe", ("VCE", "TSF")),
    ("Amsterdam", "europe", ("AMS",)),
    ("Spain", "europe", ("BCN", "MAD", "AGP", "PMI", "IBZ", "VLC", "SVQ")),
    ("Switzerland", "europe", ("ZRH", "GVA")),
    ("Lisbon", "europe", ("LIS",)),
    ("Ireland", "europe", ("DUB", "SNN")),
    ("Germany", "europe", ("BER", "MUC", "FRA")),
    ("Scandinavia", "europe", ("CPH", "ARN", "HEL")),
    ("Greece", "europe", ("ATH", "JTR", "HER")),
    ("Istanbul", "europe", ("IST", "SAW")),
    ("Croatia", "europe", ("DBV", "SPU", "ZAG")),
    ("Prague", "europe", ("PRG",)),
    ("Vienna", "europe", ("VIE",)),
    ("Budapest", "europe", ("BUD",)),
    ("Dubai", "mideast", ("DXB", "AUH")),
    ("Egypt", "mideast", ("CAI",)),
    ("Morocco", "africa", ("RAK", "CMN", "FEZ")),
    ("South Africa", "africa", ("CPT", "JNB")),
    ("Kenya Safari", "africa", ("NBO",)),
    ("Tanzania", "africa", ("JRO", "ZNZ")),
    ("India", "asia", ("DEL", "BOM", "AGR")),
    ("Nepal", "asia", ("KTM",)),
    ("Bali", "asia", ("DPS",)),
    ("Maldives", "asia", ("MLE",)),
    ("Sri Lanka", "asia", ("CMB",)),
    ("Angkor Wat", "asia", ("REP",)),
    ("South Korea", "asia", ("ICN", "GMP")),
    ("Hong Kong", "asia", ("HKG",)),
    ("China", "asia", ("PEK", "PVG", "PKX")),
    ("Taiwan", "asia", ("TPE",)),
    ("Peru", "southamerica", ("CUZ", "LIM")),
    ("Galapagos", "southamerica", ("GPS", "UIO")),
    ("Chile", "southamerica", ("SCL",)),
    ("Colombia", "southamerica", ("BOG", "CTG", "MDE")),
    ("Bolivia", "southamerica", ("VVI", "LPB")),
    ("Uruguay", "southamerica", ("MVD",)),
    ("Australia", "oceania", ("SYD", "MEL", "BNE")),
    ("Fiji", "oceania", ("NAN",)),
    ("Tahiti", "oceania", ("PPT",)),
)

AIRPORTS = {
    "AEP": "Buenos Aires, Argentina",
    "AGP": "Malaga, Spain",
    "AGR": "Agra, India",
    "AKL": "Auckland, New Zealand",
    "AMS": "Amsterdam, Netherlands",
    "ARN": "Stockholm, Sweden",
    "ATH": "Athens, Greece",
    "ATL": "Atlanta, GA",
    "AUA": "Aruba",
    "AUH": "Abu Dhabi, UAE",
    "AUS": "Austin, TX",
    "BCN": "Barcelona, Spain",
    "BER": "Berlin, Germany",
    "BGI": "Bridgetown, Barbados",
    "BGO": "Bergen, Norway",
    "BGY": "Milan, Italy",
    "BKK": "Bangkok, Thailand",
    "BNA": "Nashville, TN",
    "BNE": "Brisbane, Australia",
    "BOG": "Bogota, Colombia",
    "BOM": "Mumbai, India",
    "BOS": "Boston, MA",
    "BRC": "Bariloche, Argentina",
    "BSB": "Brasilia, Brazil",
    "BUD": "Budapest, Hungary",
    "BUR": "Burbank, CA",
    "BWI": "Baltimore, MD",
    "BZE": "Belize City, Belize",
    "BZN": "Bozeman, MT",
    "CAI": "Cairo, Egypt",
    "CDG": "Paris, France",
    "CGK": "Jakarta, Indonesia",
    "CHC": "Christchurch, New Zealand",
    "CIA": "Rome, Italy",
    "CLT": "Charlotte, NC",
    "CMB": "Colombo, Sri Lanka",
    "CMN": "Casablanca, Morocco",
    "CPH": "Copenhagen, Denmark",
    "CPT": "Cape Town, South Africa",
    "CTG": "Cartagena, Colombia",
    "CUN": "Cancun, Mexico",
    "CUR": "Curacao",
    "CUZ": "Cusco, Peru",
    "CZM": "Cozumel, Mexico",
    "DAL": "Dallas, TX",
    "DBV": "Dubrovnik, Croatia",
    "DCA": "Washington, DC",
    "DEL": "Delhi, India",
    "DEN": "Denver, CO",
    "DFW": "Dallas, TX",
    "DMK": "Bangkok, Thailand",
    "DPS": "Bali, Indonesia",
    "DTW": "Detroit, MI",
    "DUB": "Dublin, Ireland",
    "DXB": "Dubai, UAE",
    "EWR": "Newark, NJ",
    "EZE": "Buenos Aires, Argentina",
    "FCO": "Rome, Italy",
    "FEZ": "Fez, Morocco",
    "FLL": "Fort Lauderdale, FL",
    "FLR": "Florence, Italy",
    "FRA": "Frankfurt, Germany",
    "FTE": "El Calafate, Argentina",
    "FUK": "Fukuoka, Japan",
    "GIG": "Rio de Janeiro, Brazil",
    "GMP": "Seoul, South Korea",
    "GPS": "Galapagos, Ecuador",
    "GRU": "Sao Paulo, Brazil",
    "GUA": "Guatemala City, Guatemala",
    "GVA": "Geneva, Switzerland",
    "HAN": "Hanoi, Vietnam",
    "HAV": "Havana, Cuba",
    "HEL": "Helsinki, Finland",
    "HER": "Crete, Greece",
    "HKG": "Hong Kong",
    "HND": "Tokyo, Japan",
    "HNL": "Honolulu, HI",
    "IAD": "Washington, DC",
    "IBZ": "Ibiza, Spain",
    "ICN": "Seoul, South Korea",
    "IST": "Istanbul, Turkey",
    "JAC": "Jackson Hole, WY",
    "JFK": "New York, NY",
    "JNB": "Johannesburg, South Africa",
    "JRO": "Kilimanjaro, Tanzania",
    "JTR": "Santorini, Greece",
    "KEF": "Reykjavik, Iceland",
    "KIN": "Kingston, Jamaica",
    "KIX": "Osaka, Japan",
    "KOA": "Kona, HI",
    "KTM": "Kathmandu, Nepal",
    "KUL": "Kuala Lumpur, Malaysia",
    "LAS": "Las Vegas, NV",
    "LAX": "Los Angeles, CA",
    "LGA": "New York, NY",
    "LGB": "Long Beach, CA",
    "LGW": "London, UK",
    "LHR": "London, UK",
    "LIH": "Kauai, HI",
    "LIM": "Lima, Peru",
    "LIN": "Milan, Italy",
    "LIR": "Liberia, Costa Rica",
    "LIS": "Lisbon, Portugal",
    "LPB": "La Paz, Bolivia",
    "MAD": "Madrid, Spain",
    "MBJ": "Montego Bay, Jamaica",
    "MCO": "Orlando, FL",
    "MDE": "Medellin, Colombia",
    "MDW": "Chicago, IL",
    "MEL": "Melbourne, Australia",
    "MEX": "Mexico City, Mexico",
    "MIA": "Miami, FL",
    "MLE": "Male, Maldives",
    "MNL": "Manila, Philippines",
    "MSP": "Minneapolis, MN",
    "MSY": "New Orleans, LA",
    "MUC": "Munich, Germany",
    "MVD": "Montevideo, Uruguay",
    "MXP": "Milan, Italy",
    "NAN": "Nadi, Fiji",
    "NAS": "Nassau, Bahamas",
    "NBO": "Nairobi, Kenya",
    "NCE": "Nice, France",
    "NRT": "Tokyo, Japan",
    "OAK": "Oakland, CA",
    "OGG": "Maui, HI",
    "ONT": "Ontario, CA",
    "ORD": "Chicago, IL",
    "ORY": "Paris, France",
    "OSL": "Oslo, Norway",
    "PDX": "Portland, OR",
    "PEK": "Beijing, China",
    "PHL": "Philadelphia, PA",
    "PHX": "Phoenix, AZ",
    "PKX": "Beijing, China",
    "PLS": "Turks & Caicos",
    "PMI": "Mallorca, Spain",
    "POS": "Port of Spain, Trinidad",
    "PPT": "Papeete, French Polynesia",
    "PRG": "Prague, Czechia",
    "PSA": "Pisa, Italy",
    "PSP": "Palm Springs, CA",
    "PTY": "Panama City, Panama",
    "PUJ": "Punta Cana, DR",
    "PUQ": "Punta Arenas, Chile",
    "PVG": "Shanghai, China",
    "PVR": "Puerto Vallarta, Mexico",
    "RAK": "Marrakesh, Morocco",
    "REC": "Recife, Brazil",
    "REP": "Siem Reap, Cambodia",
    "RGN": "Yangon, Myanmar",
    "RTB": "Roatan, Honduras",
    "SAN": "San Diego, CA",
    "SAP": "San Pedro Sula, Honduras",
    "SAW": "Istanbul, Turkey",
    "SCL": "Santiago, Chile",
    "SDQ": "Santo Domingo, DR",
    "SEA": "Seattle, WA",
    "SFO": "San Francisco, CA",
    "SGN": "Ho Chi Minh City, Vietnam",
    "SIN": "Singapore",
    "SJC": "San Jose, CA",
    "SJD": "Los Cabos, Mexico",
    "SJO": "San Jose, Costa Rica",
    "SJU": "San Juan, PR",
    "SLC": "Salt Lake City, UT",
    "SNA": "Santa Ana, CA",
    "SNN": "Shannon, Ireland",
    "SPU": "Split, Croatia",
    "SSA": "Salvador, Brazil",
    "STN": "London, UK",
    "SVQ": "Seville, Spain",
    "SYD": "Sydney, Australia",
    "TPE": "Taipei, Taiwan",
    "TRD": "Trondheim, Norway",
    "TSF": "Venice, Italy",
    "UIO": "Quito, Ecuador",
    "USH": "Ushuaia, Argentina",
    "UVF": "St. Lucia",
    "VCE": "Venice, Italy",
    "VIE": "Vienna, Austria",
    "VLC": "Valencia, Spain",
    "VVI": "Santa Cruz, Bolivia",
    "WLG": "Wellington, New Zealand",
    "YTZ": "Toronto, Canada",
    "YUL": "Montreal, Canada",
    "YVR": "Vancouver, Canada",
    "YYC": "Calgary, Canada",
    "YYZ": "Toronto, Canada",
    "ZAG": "Zagreb, Croatia",
    "ZNZ": "Zanzibar, Tanzania",
    "ZRH": "Zurich, Switzerland",
}
